module.exports.Links_Server = [
    {
        name: "01.utilisateur",
        id: "id",
        pseudo: "pseudo",
        email: "email",
        password: "password",
        name: "name",
        photo_profil: "photo_profil",
        age: "age",
        taille: "taille",
        poids: "poids",
        masse_grasse: "masse_grasse",
        titre: "titre",
        objectif: "objectif",
        follower_total: "follower_total",
        note_modo: "note_modo",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        name: "02.adresse_ip",
        id: "id",
        user_id: "user_id",
        adresse_ip: "adresse_ip",
        date_ajout: "date_ajout",
    },
    {
        name: "03.user_lock",
        id: "id",
        user_id: "user_id",
        user_id_lock: "user_id_lock",
        date_ajout: "date_ajout",
    },
    {
        name: "04.media",
        id: "id",
        element_id_table: "user_recette_commentaire_alimentation_message_signalement_id",
        element_type_table: "type_user_recette_commentaire_alimentation_message_signalement",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        name: "05.signalement",
        id: "id",
        user_id: "user_id",
        sujet: "sujet",
        contenu: "contenu",
        element_id_table: "user_recette_commentaire_alimentation_message_signalement_id",
        note_modo: "note_modo",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
        date_resolution: "date_resolution",
    },
    {
        name: "06.follow",
        id: "id",
        user_id: "user_id",
        element_id_table: "recette_user_id",
        element_type_table: "type_recette_user",
        date_ajout: "date_ajout",
    },
    {
        name: "07.likes",
        id: "id",
        user_id: "user_id",
        element_id_table: "recette_commentaire_id",
        element_type_table: "type_recette_commentaire",
        user_id_post: "user_id_post",
        date_ajout: "date_ajout",
    },
    {
        name: "08.conversation",
        id: "id",
        user_id: "user_id",
        conversation_id: "conversation_id",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        name: "09.classification_conversation",
        id: "id",
        user_id: "user_id",
        conversation_id: "conversation_id",
        type: "type",
    },
    {
        name: "10.messages",
        id: "id",
        user_id: "user_id",
        conversation_id: "conversation_id",
        contenu: "contenu",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        name: "11.commentaire",
        id: "id",
        user_id: "user_id",
        contenu: "contenu",
        like_total: "like_total",
        recette_id: "recette_id",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        name: "12.commentaire_edit",
        id: "id",
        commentaire_id: "commentaire_id",
        contenu: "contenu",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        name: "13.recettes",
        id: "id",
        user_id: "user_id",
        name: "name",
        description: "description",
        etape_preparation: "etape_preparation",
        nutri_score: "nutri_score",
        calorie: "calorie",
        duree_recette: "duree_recette",
        like_total: "like_total",
        follower_total: "follower_total",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        name: "14.recettes_edit",
        id: "id",
        name: "name",
        description: "description",
        etape_preparation: "etape_preparation",
        nutri_score: "nutri_score",
        calorie: "calorie",
        duree_recette: "duree_recette",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        name: "15.contenu_recette",
        id: "id",
        recette_id: "recette_id",
        type: "type_recette_edit_delet",
        element_id_table: "ingredient_ustensil_id",
        element_type_table: "type_ingredient_ustensil",
        quantite: "quantite",
        type_all: "type_all",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        name: "16.consommation",
        id: "id",
        user_id: "user_id",
        recette_id: "recette_id",
        pourcentage: "pourcentage",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        name: "17.macro_micro",
        id: "id",
        nom: "nom",
        description: "description",
        abreviation: "abreviation",
        icon: "icon",
        date_ajout: "date_ajout",
    },
    {
        name: "18.ustensil",
        id: "id",
        nom: "nom",
        description: "description",
        abreviation: "abreviation",
        lien_affiliation: "lien_affiliation",
        marque: "marque",
        icon: "icon",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        name: "19.ingredient",
        id: "id",
        nom: "nom",
        description: "description",
        abreviation: "abreviation",
        calorie: "calorie",
        lien_affiliation: "lien_affiliation",
        marque: "marque",
        icon: "icon",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        name: "20.contenu_ingredient",
        id: "id",
        macro_micro_id: "macro_micro_id",
        ingredient_id: "ingredient_id",
        quantite: "quantite",
        date_ajout: "date_ajout",
    },
    {
        name: "21.recettes_deletes",
        id: "id",
        recette_id: "recette_id",
        user_id: "user_id",
        name: "name",
        description: "description",
        etape_preparation: "etape_preparation",
        nutri_score: "nutri_score",
        calorie: "calorie",
        duree_recette: "duree_recette",
        like_total: "like_total",
        follower_total: "follower_total",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
]