module.exports.Links_Server = [
    {
        table: "01_utilisateur",
        id: "id",
        pseudo: "pseudo",
        email: "email",
        valid: "confirm_email",
        password: "password",
        check: "code_check",
        first_name: "first_name",
        last_name: "last_name",
        photo_profil: "photo_profil",
        sexe: "sexe",
        age: "age",
        taille: "taille",
        poids: "poids",
        masse_grasse: "masse_grasse",
        titre: "titre",
        objectif: "objectif",
        follower_total: "follower_total",
        note_modo: "note_modo",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        table: "02_adresse_ip",
        id: "id",
        user_id: "user_id",
        adresse_ip: "adresse_ip",
        date_ajout: "date_ajout",
    },
    {
        table: "03_user_lock",
        id: "id",
        user_id: "user_id",
        user_id_lock: "user_id_lock",
        date_ajout: "date_ajout",
    },
    {
        table: "04_media",
        id: "id",
        adress: "adress",
        element_id_table: "user_recette_commentaire_alimentation_message_signalement_id",
        element_type_table: "type_user_recette_commentaire_alimentation_message_signalement",
        specifique: "specifique",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        table: "05_signalement",
        id: "id",
        user_id: "user_id",
        sujet: "sujet",
        contenu: "contenu",
        element_id_table: "user_recette_commentaire_alimentation_message_signalement_id",
        note_modo: "note_modo",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
        date_resolution: "date_resolution",
    },
    {
        table: "06_follow",
        id: "id",
        user_id: "user_id",
        element_id_table: "recette_user_id",
        element_type_table: "type_recette_user",
        date_ajout: "date_ajout",
    },
    {
        table: "07_likes",
        id: "id",
        user_id: "user_id",
        element_id_table: "recette_commentaire_id",
        element_type_table: "type_recette_commentaire",
        user_id_post: "user_id_post",
        date_ajout: "date_ajout",
    },
    {
        table: "08_conversation",
        id: "id",
        user_id: "user_id",
        conversation_id: "conversation_id",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        table: "09_classification_conversation",
        id: "id",
        user_id: "user_id",
        conversation_id: "conversation_id",
        type: "type",
    },
    {
        table: "10_messages",
        id: "id",
        user_id: "user_id",
        conversation_id: "conversation_id",
        contenu: "contenu",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        table: "11_commentaire",
        id: "id",
        user_id: "user_id",
        contenu: "contenu",
        like_total: "like_total",
        recette_id: "recette_id",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        table: "12_commentaire_edit",
        id: "id",
        commentaire_id: "commentaire_id",
        contenu: "contenu",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        table: "13_recettes",
        id: "id",
        user_id: "user_id",
        name: "name",
        description: "description",
        nutri_score: "nutri_score",
        calorie: "calorie",
        duree_recette: "duree_recette",
        like_total: "like_total",
        follower_total: "follower_total",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        table: "14_recettes_edit",
        id: "id",
        name: "name",
        description: "description",
        etape_preparation: "etape_preparation",
        nutri_score: "nutri_score",
        calorie: "calorie",
        duree_recette: "duree_recette",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        table: "15_contenu_recette",
        id: "id",
        recette_id: "recette_id",
        type: "type_recette_edit_delet",
        element_id_table: "ingredient_ustensil_id",
        element_type_table: "type_ingredient_ustensil_repas",
        quantite: "quantite",
        date_ajout: "date_ajout",
    },
    {
        table: "16_etape_preparation",
        id: "id",
        recette_id: "recette_id",
        type: "type_recette_edit_delet",
        contenu: "contenu",
        num_etape: "num_etape",
        date_ajout: "date_ajout",
    },
    {
        table: "17_consommation",
        id: "id",
        user_id: "user_id",
        recette_id: "recette_id",
        pourcentage: "pourcentage",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
    },
    {
        table: "18_macro_micro",
        id: "id",
        name: "name",
        description: "description",
        abreviation: "abreviation",
        type: "type",
        icon: "icon",
        date_ajout: "date_ajout",
    },
    {
        table: "19_ingredient",
        id: "id",
        user_id: "user_id",
        name: "name",
        description: "description",
        abreviation: "abreviation",
        calorie: "calorie",
        lien_affiliation: "lien_affiliation",
        marque: "marque",
        icon: "icon",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        table: "20_contenu_ingredient",
        id: "id",
        other_table_id: "macro_micro_type_id",
        type: "type_marco_micro_type",
        ingredient_id: "ingredient_id",
        quantite: "quantite",
        date_ajout: "date_ajout",
    },
    {
        table: "21_ustensil",
        id: "id",
        user_id: "user_id",
        name: "name",
        description: "description",
        abreviation: "abreviation",
        lien_affiliation: "lien_affiliation",
        marque: "marque",
        icon: "icon",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        table: "22_repas",
        id: "id",
        name: "name",
        description: "description",
        abreviation: "abreviation",
        icon: "icon",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        table: "23_type_produit",
        id: "id",
        name: "name",
        description: "description",
        abreviation: "abreviation",
        icon: "icon",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
    {
        table: "24_recettes_deletes",
        id: "id",
        recette_id: "recette_id",
        user_id: "user_id",
        name: "name",
        description: "description",
        etape_preparation: "etape_preparation",
        nutri_score: "nutri_score",
        calorie: "calorie",
        duree_recette: "duree_recette",
        like_total: "like_total",
        follower_total: "follower_total",
        etat_validation: "etat_validation",
        date_ajout: "date_ajout",
        date_maj: "date_maj",
    },
]

module.exports.Regex =[
    {
        id: 0,
        type: "contient que des lettres", 
        value: /[a-zA-ZÀ-ÿ -]+/,
    },
    {
        id: 1,
        type: "chiffre et lettre et espace", 
        value: /^[a-zA-Z0-9 ]*$/,
    },
    {
        id: 2,
        type: "chiffre et point", 
        value: /^[\d.,]+$/,
    },
    {
        id: 3,
        type: "uniquement chiffre et lettre", 
        value: /^[a-zA-Z0-9]*$/,
    },
    {
        id: 4,
        type: "maximum 2 caractère identique", 
        value: /^(?:(?!(\w)\1{2,}).)*$/,
    },
    {
        id: 5,
        type: "2 lettre / chiffre et 1 maj", 
        value: /^(?=(?:\D*\d){2})(?=[^A-Z]*[A-Z])/,
    },
    {
        id: 6,
        type: "lettre minuscule/maj accent et espace", 
        value: /[a-zA-ZÀ-ÿ -]+/,
    },
    {
        id: 7,
        type: "date au format jj/mm/dddd", 
        value: /^(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[0-2])\/\d{4}$/,
    },
    {
        id: 8,
        type: "date entre 1900 et 2015", 
        value: /^(19[0-9][0-9]|20[0-1][0-5])$/,
    },
    {
        id: 9,
        type: "chiffre", 
        value: /^[0-9]$/,
    },
    {
        id: 10,
        type: "pas de donnée entre <> et {}", 
        value: /^(?!.*?<.*?>)(?!.*?\{.*?\}).*$/,
   },
   {
        id: 11,
        type: "uniquement chiffre et lettre", 
        value: /^[a-zA-Z0-9 ]*$/,
   },
   {
    id: 12,
    type: "pas de donnée entre <> et {}", 
    value: /^(?!.*?<.*?>)(?!.*?\{.*?\}).*$/,
},    
]